name: Command Line Game CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - name: build the application
      run: make build
    - name: build the test file
      run: make buildtests
    - name: run the tests
      run: make runtests
    - name: remove the test file
      run: make cleantests