name: Command Line Game CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30 
    steps:   # Update references
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodules
        id: update
        run: git submodule update --remote --recursive 

      - name: Install Boost
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev

      - name: Build the necessary files
        run: |
          ls
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -B build

      - name: Build the application
        run: make -C build CLG

      - name: Build the tests for the application
        run: make -C build CLG_Tests

      - name: Run the test file
        run: ./build/tests/CLG_Tests
