name: Command Line Game CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - name: build the nessisary files
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -B build
    - name: move into the build folder
      run: cd build
    - name: build the application
      run: make
    - name: Build the tests for the application
      run: make CLG_Tests
    - name: run the test file
      run: ./CLG_Tests