name: Command Line Game CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 30 
    strategy:
      fail-fast: true
      matrix:
        build-configuration: [ Debug, Release]

    steps:   
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Build the necessary files
        run: |
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.build-configuration}} -B build

      - name: Build the application
        run: |
          make -C build CLG

      - name: Build the tests for the application
        run: |
          make -C build CLG_Tests

      - name: Run the test file
        run: |
          ./build/tests/CLG_Tests
